
name: "Continuous Integration"

on:
    push:
        branches:
            - master
            - integration
    pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest -r requirements/production
    - name: Run non-regression test sets
      run: python -m pytest -s tests/
   
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 -r requirements/production
    - name: Run linting script to determine syntax errors
      run: |
        flake8 music_browser/
        
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit -r requirements/production
    - name: Run security issues checks
      run: |
        bandit -r music_browser/
